name: build and deploy to S3 with cloudfront

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{secrets.TOKEN}}
          

      - name: install dependencies and build
        run: |
          yarn install
          yarn build 



  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: 'us-east-1'

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://bijay-cicd-bucket/

  invalidate:
    runs-on: self-hosted
    needs: deploy
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: 'us-east-1'
          
      - name: invalidate cloudfront cache
        env:
          DISTRIBUTION_ID: ${{secrets.DISTRIBUTION_ID}}
          
        run: |
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

  increaseVersion:
    runs-on: self-hosted
    needs: invalidate
    steps:
      - name: Increase the package version
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.USERNAME}}
          npm version patch
          git add .
          git commit -m "package version increased"
          git push origin main
          
        
          

